# Generated by Django 3.1 on 2020-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='alt_phone',
            field=models.IntegerField(),
        ),
    ]
